name: Check code

on:
  push:
    branches: [develop]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Install expo-cli
        run: npm install expo-cli
      - name: Check lint
        run: npm run lint
      - name: Publish
        run: npx expo publish --release-channel development --non-interactive