name: Check code

on:
  push:
    branches: [develop]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Check lint
        run: npm run lint
      - name: Install expo-cli
        run: npm install expo-cli
      - name: Check env variables
        run: node -e "console.log(process.env)"
      - name: Expo authenticate
        env:
          EXPO_CLI_PASSWORD: ${{ secrets.EXPO_CLI_PASSWORD }}
        run: npx expo login --non-interactive -u giwiro
      - name: Publish
        run: npx expo publish --release-channel development --non-interactive